# Generated by Django 3.2 on 2021-04-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iten',
            name='categoria',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iten',
            name='nome_do_produto',
            field=models.CharField(max_length=30),
        ),
    ]
