# Generated by Django 3.2 on 2021-04-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_rename_categoria_categoria_nome_da_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome_da_categoria',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
