# Generated by Django 3.2 on 2021-05-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_iten_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iten',
            name='imagem',
            field=models.ImageField(upload_to='temp'),
        ),
    ]
