# Generated by Django 3.2 on 2021-06-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0002_auto_20210619_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='endereco',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='estado',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='geo_localizacao',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(null=True, upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome_da_empresa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone1',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone2',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='texto',
            field=models.TextField(null=True),
        ),
    ]
