# Generated by Django 3.2 on 2021-06-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0003_auto_20210620_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ddd',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
