# Generated by Django 3.2 on 2021-06-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0004_empresa_ddd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='geo_localizacao',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
