# Generated by Django 3.2 on 2021-06-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_alter_iten_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='iten',
            name='capa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='iten',
            name='imagem',
            field=models.ImageField(upload_to='temp/'),
        ),
    ]
